apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ include "agent.fullname" . }}
rules:
  # Allow management of projects
  - apiGroups: ["core.launchboxhq.io"]
    resources: ["projects"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  # Allow management of addons
  - apiGroups: [ "pkg.crossplane.io" ]
    resources: [ "configurations" ]
    verbs: [ "get", "watch", "list", "create", "update", "patch", "delete" ]