apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
