name: Helm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: agent
          repository: launchboxio/agent/helm
          tag: 0.2.0
          path: deploy/charts/agent
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false